{{- if .Values.ingress.enabled -}}
{{- $fullName := include "pingfederate.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "pingfederate.name" . }}
    helm.sh/chart: {{ include "pingfederate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ if eq .backend.service "admin" -}}
{{ include "pingfederate.fullname" $ }}{{ if $.Values.pingfederate.clustering.enabled }}-admin{{ end }}
{{- else if eq .backend.service "engine" -}}
{{ include "pingfederate.fullname" $ }}{{ if $.Values.pingfederate.clustering.enabled }}-engine{{ end }}
{{- end }}
              servicePort: {{ if eq .backend.service "admin" -}}
{{ $.Values.service.admin.port }}
{{- else if eq .backend.service "engine" -}}
{{ $.Values.service.engine.port }}
{{- end }}
        {{- end }}
  {{- end }}
{{- end }}
