# Default values for pingdelegator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pingidentity
  name: pingdelegator
  tag: 2006-4.2.0
  pullPolicy: IfNotPresent
  readinessCommand: /opt/liveness.sh
  livenessCommand: /opt/liveness.sh

pingdelegator:

  publicHostname: localhost
  
  tokenProvider:
    hostname: localhost
    port: 443
    clientId: dadmin

  pingDirectoryServer:
    hostname: pingdirectory
    port: 443
  
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git 
    SERVER_PROFILE_PATH: baseline/pingdelegator
    SERVER_PROFILE_BRANCH: master

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  runtime:
    port: 6443
    name: https

ingress:
  enabled: false
  # annotations:
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  #   kubernetes.io/ingress.class: "nginx-public"

  # hosts:
  #   - host: my.host.pingdelegator.host.com
  #     paths:
  #     - path: /
  #       backend:
  #         servicePort: 6443

  # The following section adds TLS specific configuration for the ingress descriptor.  Example:
  # tls:
  #   - secretName: tls-secret
  #     hosts:
  #       - my.host.pingdelegator.host.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 0.2
  #   memory: 256Mi
  # requests:
  #   cpu: 0.2
  #   memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
