apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "pingaccess.name" . }}
    helm.sh/chart: {{ include "pingaccess.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "pingaccess.fullname" . }}-env-vars
data:
  PING_IDENTITY_ACCEPT_EULA: {{ .Values.license.acceptEULA | quote  }}
  PA_LOG_LEVEL: {{ .Values.pingaccess.logging | quote }}
{{ toYaml .Values.pingaccess.envs | indent 2 }}
  {{- if .Values.pingaccess.clustering.enabled }}
  {{- if .Values.pingaccess.clustering.adminConsoleRole }}
  OPERATIONAL_MODE: "CLUSTERED_CONSOLE"
  {{- else }}
  OPERATIONAL_MODE: "CLUSTERED_ENGINE"
  {{- end }}
  PA_CONSOLE_HOST: "{{ .Values.pingaccess.clustering.adminHostService }}"
  {{- else }}
  OPERATIONAL_MODE: "STANDALONE"
  {{ end -}}