apiVersion: v1
kind: Service
metadata:
  name: {{ include "pingaccess.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pingaccess.name" . }}
    helm.sh/chart: {{ include "pingaccess.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if or (and (.Values.pingaccess.clustering.enabled) (.Values.pingaccess.clustering.adminConsoleRole)) (not .Values.pingaccess.clustering.enabled) }}
    - port: {{ .Values.service.admin.port }}
      targetPort: {{ .Values.service.admin.port }}
      protocol: TCP
      name: {{ .Values.service.admin.name }}
    {{ end }}
    {{- if or (and (.Values.pingaccess.clustering.enabled) (not .Values.pingaccess.clustering.adminConsoleRole)) (not .Values.pingaccess.clustering.enabled) }}
    - port: {{ .Values.service.engine.port }}
      targetPort: {{ .Values.service.engine.port }}
      protocol: TCP
      name: {{ .Values.service.engine.name }}
    {{ end }}
    {{- if and (.Values.pingaccess.clustering.enabled) (.Values.pingaccess.clustering.adminConsoleRole) }}
    - port: {{ .Values.pingaccess.clustering.service.cluster.port }}
      targetPort: {{ .Values.pingaccess.clustering.service.cluster.port }}
      protocol: TCP
      name: {{ .Values.pingaccess.clustering.service.cluster.name }}
    {{ end }}
  selector:
    app.kubernetes.io/name: {{ include "pingaccess.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
